Poggers/urls.py
from django.contrib import admin
from django.urls import path, include, re_path  
from django_registration.backends.one_step.views import RegistrationView 

from core.forms import CustomUserForm  # form di registrazione customizzato
from core.views import *

from rest_auth import urls

# la registrazione tramite api avviene con rest-auth, mentre quella degli utenti con django-registration

urlpatterns = [

    # pagine accessibili agli utenti
    path('', IndexTemplateView.as_view(), name = "entry-point"),# homepage 
    path("registration/", RegistrationView.as_view()),          # registrazione
    path("login/", LoginView.as_view()),                        # login
    path("shopping-cart/", ShoppingCartView.as_view()),         # carrello dell'utente
    path("account/", AccountView.as_view(), name = "account"),  # cambio username e email

    # pagine accessibili agli amministratori
    path('manager/user-list/', ManagerUserListView.as_view()),                      # lista degli utenti
    path('manager/article-list/', ManagerArticleListView.as_view()),                # lista degli articoli
    path('manager/article-detail/', ManagerArticleDetailView.as_view()),            # aggiunta di un articolo
    path('manager/article-detail/<int:pk>', ManagerArticleDetailView.as_view()),    # modifica di un articolo
    path("manager/shipments/", ShipmentsListView.as_view()),                        # lista degli shipment
    path("manager/shipments/<int:pk>/", ShipmentsListView.as_view()),               # shipment di un utente

    # include gli endpoint della API
    path('api/', include("users.api.urls")),
    path('api/', include("articles.api.urls")),

    # endpoint forniti da rest-auth
    # /login, /logout
    path('api/rest-auth/', include("rest_auth.urls")),

    # pagina amministrazione, accessibile solo al superuser
    path('admin/', admin.site.urls),

    # login da browsable-api, per superuser
    path('api-auth/', include("rest_framework.urls")),
]

core/forms.py
from django import forms
from django_registration.forms import RegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from creditcards.forms import CardNumberField, CardExpiryField, SecurityCodeField
from users.models import CustomUser

# estensione del form di registrazione standard per adattarlo a utenti customizzati
class CustomUserForm(RegistrationForm):

    class Meta(RegistrationForm.Meta):
        model = CustomUser

class LoginForm(AuthenticationForm):
    pass

class PaymentForm(forms.Form):
    cc_number = CardNumberField(label='Card Number')
    cc_expiry = CardExpiryField(label='Expiration Date')
    cc_code = SecurityCodeField(label='CVV/CVC')
    address = forms.CharField(max_length = 100, required = True)

class ChangeUsernameForm(forms.Form):
    username = forms.CharField(label = 'new username')

class ChangeEmailForm(forms.Form):
    email = forms.EmailField(label = 'new email')

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(widget = forms.PasswordInput(), label = "old password")
    new_password = forms.CharField(widget = forms.PasswordInput(), label = "new password")
    confirm_password = forms.CharField(widget = forms.PasswordInput(), label = "confirm new password")

class ArticleForm(forms.Form):
    name = forms.CharField(max_length = 20, label = "name", required = True)
    material = forms.CharField(max_length = 20, label = "material", required = True)
    description = forms.CharField(widget = forms.Textarea, max_length = 255)
    category = forms.CharField(max_length = 20, label = "category")
    sub_category = forms.CharField(max_length = 20, label = "sub category")
    price = forms.DecimalField(max_digits = 5, decimal_places = 2, required = True)
    image = forms.URLField(max_length = 255, label = "image (URL)")

templates/account.html
{% extends 'navbar.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container border-bottom border-primary pt-3 pb-3">
    <h2>Your Account</h2>
    <br>
    <h5>Current Username: <b id = "username"></b></h5>
    <p id = "username_errors" class = "text-danger"></p>
	<form id="username_form" method = "POST">
		{% csrf_token %}
		{{ username_form|crispy }}
        <input type="submit" class="btn btn-primary" value="Change Username"></input>
	</form>
</div>
<div class="container border-bottom border-primary pt-2 pb-3">
    <h5>Current Email: <b id = "email"></b></h5>
    <p id = "email_errors" class = "text-danger"></p>
	<form id="email_form" method = "POST">
		{% csrf_token %}
		{{ email_form|crispy }}
        <input type="submit" class="btn btn-primary" value="Change Email"></input>
	</form>
</div>
<div class="container border-bottom border-primary pt-3 pb-3">
    <p id = "password_errors" class = "text-danger"></p>
	<form id="password_form" method = "POST">
		{% csrf_token %}
		{{ password_form|crispy }}
		<input type="submit" class="btn btn-primary" value="Change Password"></input>
	</form>
</div>
<br>
<div id = "admin" class = "container">
    <h2 id = "admin">Manager Panel</h2>
    <br>
    <div class = "row container">
        <a  id = "admin" class = "btn btn-info col-3" href = "http://127.0.0.1:8000/manager/user-list/">List of Users</a>
        <div class = "col-1"></div>
        <a  id = "admin" class = "btn btn-info col-3" href = "http://127.0.0.1:8000/manager/shipments">List of Orders</a>
        <div class = "col-1"></div>
        <a  id = "admin" class = "btn btn-info col-3" href = "http://127.0.0.1:8000/manager/article-list/">Article Editor</a>
    </div>
</div>

<script>
// nascondi manager panel
$("#admin").hide();

// mostra nome utente e password, mostra il manager panel ai manager
var user = get_logged_user(function(result){
    $("#username").html(`  ${result['user']}`);
    $("#email").html(`  ${result['email']}`);
    if(result['admin']){
        $("#admin").show();
    }
    else{
        console.log(result['admin']);
    }
    return result;
});

// form cambio username
$("#username_form").on('submit', (e) =>{
    var xhr = new XMLHttpRequest();
    e.preventDefault();
    xhr.open("POST", "http://127.0.0.1:8000/api/change-credentials/");
    xhr.setRequestHeader("content-type","application/json")
    xhr.setRequestHeader("Authorization","Token "+get_cookie("token"))
    console.log(document.getElementById("id_username").value);
    xhr.send(JSON.stringify(
        {
            "username": document.getElementById("id_username").value,
        }
    ));
    xhr.onreadystatechange = function(){
        if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
            response = JSON.parse(xhr.responseText)
            if(response['username_errors'] !== undefined ){
                $("#username_errors").html(response['username_errors'])
            }else{
                window.location.href = "http://127.0.0.1:8000/account/";
            }
        }
    }
});

// form cambio email
$("#email_form").on('submit', (e) =>{
    e.preventDefault();
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "http://127.0.0.1:8000/api/change-credentials/");
    xhr.setRequestHeader("content-type","application/json")
    xhr.setRequestHeader("Authorization","Token "+get_cookie("token"))
    xhr.send(JSON.stringify(
        {
            "email": document.getElementById("id_email").value,
        }
    ));
    xhr.onreadystatechange = function(){
        if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
            response = JSON.parse(xhr.responseText)
            if(response['email_errors'] !== undefined ){
                $("#email_errors").html(response['email_errors'])
            }else{
                window.location.href = "http://127.0.0.1:8000/account/";
            }
        }
    }
});

// form cambio password
$("#password_form").on('submit', (e) =>{
    e.preventDefault();
    var xhr = new XMLHttpRequest();
    var pw_current = document.getElementById("id_current_password").value;
    var pw_new = document.getElementById("id_new_password").value;
    var pw_confirm = document.getElementById("id_confirm_password").value;

    //controlla che nuova password e password di conferma combacino
    if(pw_new === pw_confirm){
        xhr.open("POST", "http://127.0.0.1:8000/api/change-credentials/");
        xhr.setRequestHeader("content-type","application/json")
        xhr.setRequestHeader("Authorization","Token "+get_cookie("token"))
        xhr.send(JSON.stringify(
            {
                "password_current": pw_current,
                "password_new": pw_new
            }
        ));
        xhr.onreadystatechange = function(){
            if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
                response = JSON.parse(xhr.responseText)
                if(response['password_errors'] !== undefined ){
                    $("#password_errors").html(response['password_errors'])
                }else{
                    window.location.href = "http://127.0.0.1:8000/account/";
                }
            }
        }
    }else{
        $("#password_errors").html("the two new passwords don't match")
    }
});
</script>

{% endblock content %}

templates/article-detail.html
{% extends 'auth_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <h2 id = "title">Add a new article</h2>
    <form id = "add_form" method = "POST">
        {% csrf_token %}    
        {{ form|crispy }}

        {{ pk|json_script:"article_pk"}}    <!-- se l'url contiene chiave primaria, la ottiene in questo modo-->
        <input class = "btn btn-primary" id = "add" type="submit" value="Add Item">
        <input class = "btn btn-primary" id = "change" type="submit" value="Change Item">
    </form>
</div>
<br>
<p class = "container">
    <a href = "http://127.0.0.1:8000/manager/article-list/">Go Back</a>
</p>
<script>
    //nascondi pulsanti submit
    $("#add").hide();
    $("#change").hide();

    //ottiene chiave primaria dell'articolo passato tramite template
    var article_pk = JSON.parse(document.getElementById('article_pk').textContent);
    console.log(article_pk)

    //se la chiave primaria è vuota si sta aggiungendo un nuovo articolo, altrimenti se ne sta modificando uno
    //se non è vuota, carica nel form i valori già presenti con una richiesta get alla API
    if(article_pk){
        //mostra pulsante change
        $("#change").show();

        //cambia titolo
        $("#title").html("Change an existing article")

        var xhr = new XMLHttpRequest();
        xhr.open("GET", "http://127.0.0.1:8000/api/article-detail/"+article_pk);
        xhr.setRequestHeader("content-type","application/json")
        xhr.setRequestHeader('Authorization', 'Token '+ String(get_cookie('token')));
        xhr.send()
        xhr.onreadystatechange = function(){
            if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
                //ottenuti i dati dell'articolo, scrivi i loro valori sul form
                response = JSON.parse(xhr.responseText)
                $("#id_name").val(response['name']);
                $("#id_material").val(response['material']);
                $("#id_description").val(response['description']);
                $("#id_category").val(response['category']);
                $("#id_sub_category").val(response['sub_category']);
                $("#id_price").val(response['price']);
                $("#id_image").val(response['image']);
            }
        }
    }
    else{
        $("#add").show();
        //cambia titolo
        $("#title").html("Add a new article")
    }

    //submit del form
    $("#add_form").on('submit', (e) =>{ 
        e.preventDefault();
        // modifica di un articolo con patch
        if(article_pk){
            xhr = new XMLHttpRequest();
            xhr.open("PATCH", "http://127.0.0.1:8000/api/article-detail/"+article_pk);
            xhr.setRequestHeader("content-type","application/json")
            xhr.setRequestHeader('Authorization', 'Token '+ String(get_cookie('token')));
            xhr.send(JSON.stringify(
                {
                    "name": $("#id_name").val(),
                    "material": $("#id_material").val(),
                    "description": $("#id_description").val(),
                    "category": $("#id_category").val(),
                    "sub_category": $("#id_sub_category").val(),
                    "price": $("#id_price").val(),
                    "image": $("#id_image").val()
                }));
            xhr.onreadystatechange = function(){
                // risposta 200: reindirizza alla lista articoli
                if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
                    window.location.href = "http://127.0.0.1:8000/manager/article-list/";
                }
                // risposta 401: reindirzza a login
                else if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 401){
                    window.location.href = "http://127.0.0.1:8000/manager/article-list/";
                }	
            }
        }
        //aggiunta di un nuovo articolo
        else{
            xhr = new XMLHttpRequest();
            xhr.open("POST", "http://127.0.0.1:8000/api/article-detail/create/");
            xhr.setRequestHeader("content-type","application/json")
            xhr.setRequestHeader('Authorization', 'Token '+ String(get_cookie('token')));
            xhr.send(JSON.stringify(
                {
                    "name": $("#id_name").val(),
                    "material": $("#id_material").val(),
                    "description": $("#id_description").val(),
                    "category": $("#id_category").val(),
                    "sub_category": $("#id_sub_category").val(),
                    "price": $("#id_price").val(),
                    "image": $("#id_image").val()
                }
            ));
            xhr.onreadystatechange = function(){
                // risposta 200: reindirizza alla lista articoli
                if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 201){
                    window.location.href = "http://127.0.0.1:8000/manager/article-list/";
                }
                // risposta 401: reindirzza a login
                else if(xhr.readyState == XMLHttpRequest.DONE && xhr.status == 401){
                    window.location.href = "http://127.0.0.1:8000/manager/article-list/";
                }	
            }
        }   
    });
</script>

{% endblock content %}

templates/article-list.html
{% extends 'navbar.html' %}

{% block content %}
<!-- dropdown categorie -->
{% include "categories.html" %}

<style media="screen">
        .card-size{
          width: 15rem;
          float: left;
        }
</style>

<!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<div class = "container">
    <h2>Article List</h2>
    <a class = "btn btn-success col-10" href="http://127.0.0.1:8000/manager/article-detail/" > Add new Article</a>
    <div class = "row container">
        <p class = "col-sm text-danger" id = "messages"></p>
    </div>  
</div>

<div class="container">
        <div class="row">
            <div class="col-sm">
                <!-- cards articoli -->
                <div  class="   container 
                                container-border
                                "> 
                <!-- DECK CARTE -->
                <div class="row"
                    id="container-carte">
                <!-- CARTE SINGOLE -->
        </div>
</div>
<script>
    var user = null;
    //salva localmente informazioni sugli oggetti
    var items = [];

    //se il token è scaduto, redirigi a pagina di login
    if(String(get_cookie('token')) === ''){
        window.location.href = "http://127.0.0.1:8000/login/";
    }

    //carica carrello
    get_logged_user(function(result){
        user = result;
        xhr = new XMLHttpRequest();
        xhr.open("GET", articles_url);
        xhr.setRequestHeader('Authorization', 'Token '+ String(get_cookie('token')));
        xhr.send();
        xhr.onreadystatechange = function(){
            // carica carte con oggetti del carrello
            if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
                response = JSON.parse(xhr.responseText);
                $.each(response, function(i){
                    addArticleCard(response[i]);
                    items.push(response[i]);
                });
            }	
        }
    });

    function deleteArticle(id){
        xhr = new XMLHttpRequest();
        xhr.open("DELETE", "http://127.0.0.1:8000/api/article-detail/"+id);
        xhr.setRequestHeader('Authorization', 'Token '+ String(get_cookie('token')));
        xhr.send();
        xhr.onreadystatechange = function(){
            // carica carte con oggetti del carrello
            if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 204){
                window.location.href = "http://127.0.0.1:8000/manager/article-list/"
            }	
        }
    }


    function addArticleCard(article){
        var src = article['image'];      
        var textNome = article["name"];
        var textMateriale = article["material"];
        var textDesc = article["description"];
        var textPrezzo = article["price"];


        var myCard = $(`<div class=" card card-size"> 
                            <img class="card-img-top" src='${src}'> 
                            <div class="card-body"> 
                                <h5 class="card-title">${textNome} - ${textMateriale}</h5> 
                                <p class="card-text">${textDesc}</p>
                                <p> Prezzo: ${textPrezzo} €</p>
                                <a class = "btn btn-success"
                                        href="http://127.0.0.1:8000/manager/article-detail/${article.pk}">
                                        Modifica
                                </a>
                                <button class = "btn btn-danger"
                                        onclick = "deleteArticle(${article.pk})"
                                        style = "float: right;">
                                        Elimina
                                </button>
                            </div>
                        </div>`);
        myCard.appendTo('#container-carte');
    }
</script>
{% endblock content %}

templates/auth_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Poggers</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://127.0.0.1:8000/static/js/functions.js"></script>

    <style media = "screen">
        .login-form-container{
            width: 300px;
            margin: auto;
        }

        .registration-form-container{
            width: 400px;
            margin: auto;
        }

        .outer-area{
            margin-top: 30px;
            margin-bottom: 30px;
        }

        .auth-box{
            border: 3px solid darkgrey;
            border-radius: 10px;
            padding-top: 5px;
            padding-bottom: 5px;
            width: 600px;
            margin: auto;
        }
    </style>
</head>
<body>
    <div class = "outer-area">
        <div class = "auth-box text-center">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/categories.html
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#434952; padding-top: 0px; padding-bottom: 0px;">
        <div class="navbar-brand">Categorie:</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Simulators
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="?category=simulator&sub_category=sword1h">One Handed Swords</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=simulator&sub_category=sword2h">Two Handed Swords</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=simulator&sub_category=axe">Axes</a>              
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=simulator&sub_category=polearms">Polearms</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Protections
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="?category=protections&sub_category=head">Head</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=protections&sub_category=torso">Torso</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=protections&sub_category=hands">Hands</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=protections&sub_category=legs">Legs</a>
                <div class="dropdown-divider"></div>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Shields
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="?category=shield&sub_category=buckler">Bucklers</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=shield&sub_category=targe">Targes</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="?category=shield&sub_category=rotella">Rotellas</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <script>
        articles_url = "http://127.0.0.1:8000/api/article-list/"

        //ottieni i parametri per le categorie dall'url della pagina
        var query_string = window.location.search;
        const  url_params = new URLSearchParams(query_string);
        var category =  url_params.get("category");
        var sub_category = url_params.get("sub_category");

        //se i parametri sono stati inseriti, aggiungili al percorso per ottenere gli articoli
        if(category){
            articles_url += category;
        }
        if(sub_category){
            articles_url = articles_url + "/" + sub_category
        }
      </script>

templates/index.html
<!-- HOMEPAGE -->
{% extends 'navbar.html' %}
{% load static %}


{% block content %}

<!-- dropdown categorie -->
{% include "categories.html" %}

<style media="screen">
	.card-size{
	width: 18rem;
	float: left;
	}
</style>
	<!-- messaggio di aggiunta articoli al carrello-->
	<div class = "container">
	</div>

  <!-- cards articoli -->
    <div  class=" container
				  container-border"> 
		<h5 id = "item-added" class = "mt-2 pt-2 pb-2 text-center" ></h5>
      <!-- DECK CARTE -->
      	<div class="row 
                  mt-3
                  justify-content-center"
			id="container-carte">
          <!-- CARTE SINGOLE -->
          
	  	</div>
  	</div>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<script>
		var item_added = url_params.get("item_added");
		console.log(item_added);
		if(item_added == 'true'){
			$("#item-added").html("Article added to cart");
			$("#item-added").css({"color":"#5cb85c" });
		}
		else if(item_added == 'false'){
			$("#item-added").html("You can't order more copies of this item");
			$("#item-added").css({"color":"#d9534f" });
		}
		else if(item_added == null){
			$("#item-added").html("");
		}

		xhr = new XMLHttpRequest();
		xhr.open("GET", articles_url);
		xhr.send();
		xhr.onreadystatechange = function(){
			if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
				response = JSON.parse(xhr.responseText);
				console.log(response);
				$.each(response, function(i){addCard(response[i])});
			}
		}

		function addToCart(key){
			token = get_cookie("token");
			if(token !== ''){
				console.log("chiave item: ",key)
				get_article_detail(key, function(result){
					//richiesta di aggiunta al carrello
					console.log(result);
					result["token"] = token;

					var xhr = new XMLHttpRequest();
					xhr.open("POST", "http://127.0.0.1:8000/api/add-to-cart/");
					xhr.setRequestHeader('Content-Type', 'application/json');
					xhr.send(JSON.stringify(result));

					//se la richiesta ha successo, notifica l'utente
					xhr.onreadystatechange = function(){
						if (xhr.readyState == XMLHttpRequest.DONE && xhr.status == 200){
							response = JSON.parse(xhr.responseText);
							console.log(response);
							//se non è possibile aggiungere l'articolo, ritorna un errore
							if(response['error'] !== undefined){
								window.location.href = "http://127.0.0.1:8000/"+"?item_added=false";
							}
							else if(response['message'] !== undefined){
								//altrimenti refresha la pagina e passa un parametro per indicare l'avvenuta aggiunta
								window.location.href = "http://127.0.0.1:8000/"+"?item_added=true";
							}
						}
					}
				});
			}
			else{
				window.location.href = "http://127.0.0.1:8000/login/"
			}
		}


		function user_test(){
			token = get_cookie("token");
			if(token != ''){
				xhr = new XMLHttpRequest();
				xhr.open("POST", 'http://127.0.0.1:8000/api/user-test/');
				xhr.setRequestHeader('Content-Type', 'application/json');
				data = { "token": token }
				console.log(data);
    			xhr.send(JSON.stringify(data));
			}
			else{
				console.log("utente non loggato, redirigi a login ...")
			}
			// utente non loggato
		}

	</script>
{% endblock %}

templates/login.html
{% extends 'auth_layout.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load crispy_forms_tags %}
</head>
<body>
    {% block content %}
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <div class = "container">
        <h1>Login</h1>
        <p id = "errors" class = "text-danger"></p>
        <form id = "log_form" action="" method = "post">
            {% csrf_token %}    
            {{ form|crispy }}
            <input type="submit" class = "btn btn-primary" value="Login">
        </form>
        <br>
        <div class = "mt-2">
            <a href="http://127.0.0.1:8000/registration/">Create a new Account</a>
            <p><a href="http://127.0.0.1:8000/">Return to the homepage</a></p>
        </div>
        <br>
    </div>
</body>

<script>
    var messages = []

    $("#log_form").on('submit', (e) =>{ 
        e.preventDefault();
        var username = document.getElementById("id_username").value;
        var password = document.getElementById("id_password").value;

        console.log(username)
        console.log(password)

        var tokenRequest = new XMLHttpRequest();
        tokenRequest.open("POST", "http://127.0.0.1:8000/api/rest-auth/login/")
        tokenRequest.setRequestHeader('Content-Type', 'application/json');

        tokenRequest.onreadystatechange = function(){
            if(tokenRequest.readyState == XMLHttpRequest.DONE && tokenRequest.status == 200){
                //il login ha avuto successo
                response = JSON.parse(tokenRequest.responseText);
                //setta token nei cookie, valido per 1 ora
                set_cookie("token", response['key'], 60);
                window.location.href = "http://127.0.0.1:8000/";
            }
            else if(tokenRequest.readyState == XMLHttpRequest.DONE && tokenRequest.status == 400){
                document.getElementById("errors").innerHTML = "Incorrect username or password";
                document.getElementById("id_password").value = "";  //svuota password
            }
        }

        tokenRequest.send(JSON.stringify({
            "username": username,
            "password": password,
        }));
    });
    
                    //redirige alla pagina iniziale
    //window.location.replace("http://127.0.0.1:8000/");

</script>

{% endblock content %}

</html>